# Generated by Django 5.0.6 on 2024-07-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0014_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='service',
            field=models.CharField(max_length=100),
        ),
    ]
