# Generated by Django 5.0.6 on 2024-07-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0015_alter_feedback_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
