# Generated by Django 5.0.6 on 2024-07-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0017_remove_service_man_available_slots_servicemanslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemanslot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
