# Generated by Django 5.0.6 on 2024-07-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0020_order_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_addressed',
            field=models.BooleanField(default=False),
        ),
    ]
